/*
 * A collection of Nomi's APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Restaurant'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Restaurant'));
  } else {
    // Browser globals (root is window)
    if (!root.ACollectionOfNomisApIs) {
      root.ACollectionOfNomisApIs = {};
    }
    root.ACollectionOfNomisApIs.RestaurantApi = factory(root.ACollectionOfNomisApIs.ApiClient, root.ACollectionOfNomisApIs.Restaurant);
  }
}(this, function(ApiClient, Restaurant) {
  'use strict';

  /**
   * Restaurant service.
   * @module api/RestaurantApi
   * @version 1.0.0
   */

  /**
   * Constructs a new RestaurantApi. 
   * @alias module:api/RestaurantApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the apiRestaurantsRegisterPost operation.
     * @callback module:api/RestaurantApi~apiRestaurantsRegisterPostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Creates a restaurant.
     * @param {Object} opts Optional parameters
     * @param {module:model/Restaurant} opts.name Restaurant information. Id is ignored if provided.
     * @param {module:api/RestaurantApi~apiRestaurantsRegisterPostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.apiRestaurantsRegisterPost = function(opts, callback) {
      opts = opts || {};
      var postBody = opts['name'];


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = ['application/x-www-form-urlencoded'];
      var accepts = [];
      var returnType = null;

      return this.apiClient.callApi(
        '/api/restaurants/register', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the webApiRestaurantsGet operation.
     * @callback module:api/RestaurantApi~webApiRestaurantsGetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:api/RestaurantApi~webApiRestaurantsGetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.webApiRestaurantsGet = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = [];
      var accepts = [];
      var returnType = null;

      return this.apiClient.callApi(
        '/webApi/restaurants', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
