[context.production.environment]
NODE_ENV = "development"
REACT_APP_API_BASE_URL = "https://nomi-menu-service.herokuapp.com"

[context.deploy-preview.environment]
NODE_ENV = "development"
REACT_APP_API_BASE_URL = "https://nomi-menu-service-staging.herokuapp.com"

[context.branch-deploy.environment]
NODE_ENV = "development"
REACT_APP_API_BASE_URL = "https://nomi-menu-service-staging.herokuapp.com"