[context.production.environment]
REACT_APP_API_BASE_URL = "https://nomi-menu-service.herokuapp.com"
REACT_APP_AWS_S3_BASE_URL = "https://nomi-menu-service.herokuapp.com/api/images"

[context.deploy-preview.environment]
REACT_APP_API_BASE_URL = "https://nomi-menu-service-staging.herokuapp.com"
REACT_APP_AWS_S3_BASE_URL = "https://nomi-menu-service-staging.herokuapp.com/api/images"

[context.staging.environment]
REACT_APP_API_BASE_URL = "https://nomi-menu-service-staging.herokuapp.com"
REACT_APP_GOOGLE_ANALYTICS_ID = "G-NXNMHVKZLT"
REACT_APP_AWS_S3_BASE_URL = "https://nomi-menu-service-staging.herokuapp.com/api/images"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
