[context.production.environment]
REACT_APP_API_BASE_URL = "https://nomi-menu-service.herokuapp.com"

[context.deploy-preview.environment]
REACT_APP_API_BASE_URL = "https://nomi-menu-service-testing.herokuapp.com"

[context.develop.environment]
REACT_APP_API_BASE_URL = "https://nomi-menu-service-testing.herokuapp.com"

[context.master.environment]
REACT_APP_API_BASE_URL = "https://nomi-menu-service-staging.herokuapp.com"
REACT_APP_GOOGLE_ANALYTICS_ID = "G-NXNMHVKZLT"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
