[context.production.environment]
NODE_ENV = "production"
REACT_APP_API_BASE_URL = "https://nomi-menu-service.herokuapp.com"
REACT_APP_GOOGLE_ANALYTICS_ID="G-1V27CCNXDJ"

[context.deploy-preview.environment]
NODE_ENV = "production"
REACT_APP_API_BASE_URL = "https://nomi-menu-service-testing.herokuapp.com"

[context.master.environment]
NODE_ENV = "production"
REACT_APP_API_BASE_URL = "https://nomi-menu-service-staging.herokuapp.com"
REACT_APP_GOOGLE_ANALYTICS_ID="G-NXNMHVKZLT"

[context.develop.environment]
NODE_ENV = "production"
REACT_APP_API_BASE_URL = "https://nomi-menu-service-testing.herokuapp.com"


[[redirects]]
from = "/*"
to = "/index.html"
status = 200
