[context.production.environment]
NODE_ENV = "production"
GATSBY_API_URL = "https://nomi-menu-service.herokuapp.com"

[context.deploy-preview.environment]
NODE_ENV = "production"
GATSBY_API_URL = "https://nomi-menu-service-testing.herokuapp.com"

[context.master.environment]
NODE_ENV = "production"
GATSBY_API_URL = "https://nomi-menu-service-staging.herokuapp.com"

[context.develop.environment]
NODE_ENV = "production"
GATSBY_API_URL = "https://nomi-menu-service-testing.herokuapp.com"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
