/*
 * A collection of Nomi's APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ACollectionOfNomisApIs);
  }
}(this, function(expect, ACollectionOfNomisApIs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ACollectionOfNomisApIs.DefaultApi();
  });

  describe('(package)', function() {
    describe('DefaultApi', function() {
      describe('apiAssetsPathGet', function() {
        it('should call apiAssetsPathGet successfully', function(done) {
          // TODO: uncomment, update parameter values for apiAssetsPathGet call
          /*
          var path = "path_example";

          instance.apiAssetsPathGet(path, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
