/*
 * A collection of Nomi's APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ACollectionOfNomisApIs);
  }
}(this, function(expect, ACollectionOfNomisApIs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ACollectionOfNomisApIs.UserApi();
  });

  describe('(package)', function() {
    describe('UserApi', function() {
      describe('apiUserLoginPost', function() {
        it('should call apiUserLoginPost successfully', function(done) {
          // TODO: uncomment, update parameter values for apiUserLoginPost call
          /*
          var opts = {};
          opts.email = "email_example";
          opts.password = "password_example";

          instance.apiUserLoginPost(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiUserRegisterPost', function() {
        it('should call apiUserRegisterPost successfully', function(done) {
          // TODO: uncomment, update parameter values for apiUserRegisterPost call
          /*
          var opts = {};
          opts.user = new ACollectionOfNomisApIs.User();
          opts.user.id = "0";
          opts.user.email = "";
          opts.user.username = "";
          opts.user.password = "";
          opts.user.role = "";

          instance.apiUserRegisterPost(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
