/*
 * A collection of Nomi's APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Category', 'model/Tag'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Category'), require('./Tag'));
  } else {
    // Browser globals (root is window)
    if (!root.ACollectionOfNomisApIs) {
      root.ACollectionOfNomisApIs = {};
    }
    root.ACollectionOfNomisApIs.Dish = factory(root.ACollectionOfNomisApIs.ApiClient, root.ACollectionOfNomisApIs.Category, root.ACollectionOfNomisApIs.Tag);
  }
}(this, function(ApiClient, Category, Tag) {
  'use strict';

  /**
   * The Dish model module.
   * @module model/Dish
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Dish</code>.
   * @alias module:model/Dish
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>Dish</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Dish} obj Optional instance to populate.
   * @return {module:model/Dish} The populated <code>Dish</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('notes'))
        obj.notes = ApiClient.convertToType(data['notes'], 'String');
      if (data.hasOwnProperty('tableTalkPoints'))
        obj.tableTalkPoints = ApiClient.convertToType(data['tableTalkPoints'], 'String');
      if (data.hasOwnProperty('categoryId'))
        obj.categoryId = ApiClient.convertToType(data['categoryId'], 'Number');
      if (data.hasOwnProperty('category'))
        obj.category = Category.constructFromObject(data['category']);
      if (data.hasOwnProperty('restaurantId'))
        obj.restaurantId = ApiClient.convertToType(data['restaurantId'], 'Number');
      if (data.hasOwnProperty('tags'))
        obj.tags = ApiClient.convertToType(data['tags'], [Tag]);
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * @member {String} description
   */
  exports.prototype.description = undefined;

  /**
   * @member {String} notes
   */
  exports.prototype.notes = undefined;

  /**
   * @member {String} tableTalkPoints
   */
  exports.prototype.tableTalkPoints = undefined;

  /**
   * @member {Number} categoryId
   */
  exports.prototype.categoryId = undefined;

  /**
   * @member {module:model/Category} category
   */
  exports.prototype.category = undefined;

  /**
   * @member {Number} restaurantId
   */
  exports.prototype.restaurantId = undefined;

  /**
   * @member {Array.<module:model/Tag>} tags
   */
  exports.prototype.tags = undefined;

  return exports;

}));
