version: 2.1

orbs:
  # heroku: circleci/heroku@x.y
  node: circleci/node@4.2.0

jobs:
  release:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - node/install-packages
      - run: npx semantic-release

workflows:
  release:
    jobs:
      - release:
          filters:
            branches:
              only:
                - staging
                - production
