/*
 * A collection of Nomi's APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ACollectionOfNomisApIs);
  }
}(this, function(expect, ACollectionOfNomisApIs) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Tag', function() {
      beforeEach(function() {
        instance = new ACollectionOfNomisApIs.Tag();
      });

      it('should create an instance of Tag', function() {
        // TODO: update the code to test Tag
        expect(instance).to.be.a(ACollectionOfNomisApIs.Tag);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property type (base name: "type")', function() {
        // TODO: update the code to test the property type
        expect(instance).to.have.property('type');
        // expect(instance.type).to.be(expectedValueLiteral);
      });

      it('should have the property excludeForFilter (base name: "excludeForFilter")', function() {
        // TODO: update the code to test the property excludeForFilter
        expect(instance).to.have.property('excludeForFilter');
        // expect(instance.excludeForFilter).to.be(expectedValueLiteral);
      });

      it('should have the property dishTags (base name: "dish_tags")', function() {
        // TODO: update the code to test the property dishTags
        expect(instance).to.have.property('dishTags');
        // expect(instance.dishTags).to.be(expectedValueLiteral);
      });

    });
  });

}));
