/*
 * A collection of Nomi's APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ACollectionOfNomisApIs);
  }
}(this, function(expect, ACollectionOfNomisApIs) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('TagDishTags', function() {
      beforeEach(function() {
        instance = new ACollectionOfNomisApIs.TagDishTags();
      });

      it('should create an instance of TagDishTags', function() {
        // TODO: update the code to test TagDishTags
        expect(instance).to.be.a(ACollectionOfNomisApIs.TagDishTags);
      });

      it('should have the property dishId (base name: "dishId")', function() {
        // TODO: update the code to test the property dishId
        expect(instance).to.have.property('dishId');
        // expect(instance.dishId).to.be(expectedValueLiteral);
      });

      it('should have the property tagId (base name: "tagId")', function() {
        // TODO: update the code to test the property tagId
        expect(instance).to.have.property('tagId');
        // expect(instance.tagId).to.be(expectedValueLiteral);
      });

      it('should have the property removable (base name: "removable")', function() {
        // TODO: update the code to test the property removable
        expect(instance).to.have.property('removable');
        // expect(instance.removable).to.be(expectedValueLiteral);
      });

    });
  });

}));
